# Generated by Django 3.2.2 on 2021-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNo', models.IntegerField(verbose_name='کد کالا')),
                ('ProductTitle', models.CharField(max_length=250, verbose_name='عنوان کالا')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'db_table': 'Product',
                'managed': True,
            },
        ),
    ]
